name: haven

# use:
#   date; conda env create -f ./environment.yml; date

channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge

dependencies:
  # --- Python core packages
  - python=3.9
  - ipython
  - ipykernel
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil

  # --- Compiled performance packages (e.g. numpy with MKL)
  # - numpy>=1.22
  # - pandas>=1
  # - scipy>=1.8

  # --- Random packages that aren't on pypi
  - aps-dm-api>=5 # User requested
  - epics-base>=7.0.5

  # --- Qt
  - pyqt=5 # >=5.12.0,<5.15
  - qt=5

  # --- testing and quality assurance
  - pre-commit
  - black
  - flake8
  - pylint
  - pytest
  - pytest-cov
  
  # --- general support packages
  - bitshuffle
  - epics-base>=7.0.5
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics>=3.5.0
  - pymongo
  - scikit-image
  - xlrd

  # # --- Bluesky framework packages
  # all moved to pip install (conda takes additional 10m to solve)

  # --- user-requested packages
  - aps-dm-api>=5
  - nexpy
  - punx
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - stdlogpj
  - xrayutilities
  - xraydb

  # # --- packaging and publishing
  - poetry
  - sphinx
  - conda-build
  - coverage
  - sphinxcontrib-napoleon
  - twine
  - versioneer

  - pip:
    - apstools
    - area-detector-handlers
    - bluesky-queueserver
    - bluesky-queueserver-api
    - bluesky-widgets
    - bluesky>=1.8.1
    - databroker-pack
    - databroker>=1.2.4,<2
    - hklpy
    - ophyd>=1.6.3
    - pydm
    - adl2pydm
  #   - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-webclient is NOT Python software, don't install it this way
    #    https://github.com/bluesky/bluesky-webclient
