# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
# # [build-system]
# # requires = ["setuptools>=42"]
# # build-backend = "setuptools.build_meta"


[tool.poetry]
name = "capissen38"
version = "0.1.0"
description = "Runs the spectroscopy group beamlines."

license = "MIT"

authors = [
    "Mark Wolfman <wolfman@anl.gov>"
]

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/spc-group/capissen38"
homepage = "https://github.com/spc-group/capissen38"

keywords = ["synchrotron", "xray", "bluesky"]

[tool.poetry.dependencies]
python = "^3.6"  # Compatible python versions must be declared here
toml = "^0.9"
# Dependencies with extras
# requests = { version = "^2.13", extras = [ "security" ] }
# # Python specific dependencies with prereleases allowed
# pathlib2 = { version = "^2.2", python = "~2.7", allow-prereleases = true }
# # Git dependencies
# cleo = { git = "https://github.com/sdispater/cleo.git", branch = "master" }

# # Optional dependencies (extras)
# pendulum = { version = "^1.4", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-cov = "^3.0"

# [tool.poetry.scripts]
# my-script = "my_package:main"