[tool.poetry]
name = "firefly"
version = "0.1.0"
description = "Runs the spectroscopy group beamlines."

license = "all-rights-reserved"

authors = [
    "Mark Wolfman <wolfman@anl.gov>"
]

readme = "README.md"  # Markdown files are supported

repository = "https://github.com/spc-group/firefly"
homepage = "https://github.com/spc-group/firefly"

keywords = ["synchrotron", "xray", "bluesky"]

[tool.poetry.dependencies]

# time-machine = {}
# autoapi = {}

# [tool.poetry.scripts]
# my-script = "my_package:main"

# Dependencies with extras
# requests = { version = "^2.13", extras = [ "security" ] }
# # Python specific dependencies with prereleases allowed
# pathlib2 = { version = "^2.2", python = "~2.7", allow-prereleases = true }
# # Git dependencies
# cleo = { git = "https://github.com/sdispater/cleo.git", branch = "master" }

# # Optional dependencies (extras)
# pendulum = { version = "^1.4", optional = true }

[tool.poetry.scripts]
start_firefly = "firefly.launcher:main"