# Defaults go here, then get updated by toml loader
[beamline]

name = "SPC Beamline (sector unknown)"
ioc_prefix = ""
vme_prefix = ""
is_connected = false

[facility]

name = "Advanced Photon Source"
xray_source = "insertion device"

[shutter]

[shutter.A]

open_pv = "PSS:99ID:FES_OPEN_EPICS.VAL"
close_pv = "PSS:99ID:FES_CLOSE_EPICS.VAL"
status_pv = "PSS:99ID:A_BEAM_PRESENT"

[undulator]

ioc = "id_ioc"

[monochromator]

ioc = "mono_ioc"
energy_ioc = "mono_ioc"  # 25-ID has the Energy motor on separate PV

[ion_chamber]

[ion_chamber.scaler]
ioc = "scaler_ioc"
record = "scaler1"

[ion_chamber.preamp]

ioc = "preamp_ioc"

# Keys for ion_chamber definitions must begin with "ch" (e.g. "ch1", "ch2")

[ion_chamber.ch2]

preamp_record = "SR570_1"

[fluorescence_detector]

[fluorescence_detector.vortex]

pv_prefix = ""


[motor]
iocs = ["vme_crate_ioc"]

[camera]

imagej_command = "imagej"

# Keys for camera definitions must begin with "cam" (e.g. "camA", "camB")

[camera.camA]

name = "s25id-gige-A"
description = "GigE Vision A"
ioc = "camA_ioc"