# Based on tutorial: https://autobencoder.com/2020-08-24-conda-actions/

name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Install micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
    # - name: Create conda environment
    #   run: |
    #     micromamba create -n haven -y -f environment-explicit.txt
    - name: Activate conda environment
      run: |
        micromamba activate haven
    # - name: Install any missing dependencies (mostly via pip)
    #   run: |
    #     pip install time-machine autoapi pytest-mongodb        
    - name: Install haven
      run: poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false      
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
